name: perde_ar
description: Perde görselleştirme MVP
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Bir sonraki adımda kullanacağız (şimdilik ekli dursun)
  camera: ^0.10.6
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  image: ^3.3.0
  vector_math: ^2.1.4
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  tflite_flutter: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/ml/


